### PR TITLE
Add gui ver0.1

### PR DESCRIPTION
**Pull request by Yuan-ManX**

### CODE REVIEW

**Comment by RVC-Boss** [comment]
I'll test the GUI version later. There have been quite a few code updates this week. Are you planning to update the GUI code as well?
我后面测试一下gui版本。这一周有挺多代码更新，你还准备更新gui的代码吗？

**Comment by Yuan-ManX** [comment]
Ok, I will update the latest gui code.
好的，我更新一下最新的gui的代码

**Comment by RVC-Boss** [comment]
I have merged the latest gui.py
Is there any requirements for pyqt?

**Comment by RVC-Boss** [comment]
ps: 你应该尽量通过import复用inference_gui.py的代码，否则日后inference_gui.py的代码如果有变化，你需要在gui.py中手工变化
ps: You should try to reuse the code from inference_gui.py through import. Otherwise, if there are changes to the code in inference_gui.py in the future, you will need to manually update it in gui.py.

**Comment by Yuan-ManX** [comment]
OK! I think it's a great idea. I will update the latest code accordingly.
OK！好主意，我更新一下最新的代码

**Pull request closed without merging**
