### PR TITLE
fix progress bar

### PR DESCRIPTION
**Pull request by pengzhendong**

### CODE REVIEW

**Comment by RVC-Boss** [comment]
I haven't encountered any bugs using the codes now. How did the code run before and after you submitted it? Please take screenshots.
image

**Comment by pengzhendong** [comment]
There should be a progress bar to show the percentage.

**Comment by RVC-Boss** [comment]
> There should be a progress bar to show the percentage.
> 
> 100%|████████████████| 100/100 [00:00<00:00, 4.91it/s]

let me have a try

**Comment by RVC-Boss** [comment]
> There should be a progress bar to show the percentage.
> 
> 100%|████████████████| 100/100 [00:00<00:00, 4.91it/s]

Nice!

**Pull request merged**
