### PR TITLE
添加 faster whisper 转写多种语言的入口和相关脚本，提高效率

### PR DESCRIPTION
**Pull request by v3ucn**
添加 faster whisper 转写多种语言的入口和相关脚本，提高效率

### CODE REVIEW

**Comment by RVC-Boss** [comment]
挺好的，后续有调研其他whisper模型不，比如日文英文的，还有insanely-fast-whisper

**Comment by v3ucn** [comment]
好的，回头测试一下

**Comment by bfloat16** [comment]
推荐用faster_whisper，结合VAD最大程度防止whisper抽风重复（
whisper.cpp貌似也行，但集成不方便
image

**Comment by KamioRinn** [comment]
> 挺好的，后续有调研其他whisper模型不，比如日文英文的，还有insanely-fast-whisper

测了下insanely-fast-whisper效果不如faster-whisper，会出现不少乱七八糟的内容（中文、日语）。总体中文下看起来还是Funasr好。

**Comment by Chopin68** [comment]
model_version 没有定义

**Comment by company8** [comment]
@RVC-Boss Sorry to bother you. Love the project. What's the timeline for implementing Whisper ? Really excited about this project, RVC and now GPT SoVITS. Man, I respect your contribution.

**Comment by RVC-Boss** [comment]
> @RVC-Boss Sorry to bother you. Love the project. What's the timeline for implementing Whisper ? Really excited about this project, RVC and now GPT SoVITS. Man, I respect your contribution.

Done, you can update to the latest version to use it.

**Pull request closed without merging**
