### PR TITLE
fix #1240

### LINKED ISSUE #1240: It seems that the move_to_gpu & move_to_cpu is not working as expected in the branch fast_inference.
It seems that the move_to_gpu & move_to_cpu is not working as expected in the branch fast_inference.

https://github.com/RVC-Boss/GPT-SoVITS/blob/fast_inference_/api_v3.py#L327-L343

It will always move to cpu.
The custom settings device is cuda. The precision is half.

When the move_to_cpu is called, the custom settings device became cpu and the precision kept half.
But according to lines below, half is not supported for cpu.

https://github.com/RVC-Boss/GPT-SoVITS/blob/fast_inference_/GPT_SoVITS/TTS_infer_pack/TTS.py#L311-L313

I try to add the lines below to move_to_cpu.
https://github.com/RVC-Boss/GPT-SoVITS/blob/fast_inference_/api_v3.py#L348-L351
```Python
    tts.enable_half_precision(False)
```

I try to add the lines below to move_to_gpu.
https://github.com/RVC-Boss/GPT-SoVITS/blob/fast_inference_/api_v3.py#L354-L356
```Python
    tts.enable_half_precision(tts_config.is_half)
```

But then the first tts request is working. The second isn't.
Here's the error of the second request.
```
{
    "message": "tts failed",
    "Exception": "Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)"
}
```

@KevinZhang19870314

### PR DESCRIPTION
**Pull request by SetoKaiba**
Please check the #1240 here.

But I'm not sure this is the correct fix as expected. At least, it works on my side for moving between gpu and cpu.
@KevinZhang19870314

### CODE REVIEW

**Comment by SetoKaiba** [comment]
But this fix is assuming that the gpu is always available.
I'm not sure whether it's the correct fix.

**Comment by KevinZhang19870314** [comment]
@SetoKaiba Thanks for pointing out this issue.

The purpose of methods move_to_gpu & move_to_cpu is to make sure use gpu properly and also save the gpu for performance after tts inference (#1058).
According to your found in #1241, I think it caused by this line: https://github.com/RVC-Boss/GPT-SoVITS/blob/8dd7cfab931c8c98ac8ab33a213e309c7c2f737c/GPT_SoVITS/TTS_infer_pack/TTS.py#L344

So, I think the proper fix should be add a boolean prameter `save_configs` in method `set_device` to control if we should save configs in yaml file when call move_to_gpu & move_to_cpu.

@ChasonJiang What do you think?

**Comment by KevinZhang19870314** [comment]
the name of `move_to_gpu` seems not that make sence. It just move the tensors according to the tts config, if config is cpu then move to cpu, if its gpu then move to gpu.

**Comment by SetoKaiba** [comment]
@KevinZhang19870314 Thank you for your clarification. Is this new commit expected behaviour?

**Comment by KevinZhang19870314** [comment]
LGTM

Waiting for @ChasonJiang to review.

**Pull request merged**
